import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'cities'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.increments('id')
      table
        .integer('country_id')
        .unsigned()
        .references('id')
        .inTable('countries')
        .onDelete('CASCADE')
      table.string('label').notNullable()
    })

    this.defer(async (db) => {
      await db.table(this.tableName).multiInsert([
        { label: 'Algiers', country_id: 1 },
        { label: 'Oran', country_id: 1 },
        { label: 'Blida', country_id: 1 },
        { label: 'Constantine', country_id: 1 },
        { label: 'Annaba', country_id: 1 },
        { label: 'Djelfa', country_id: 1 },
        { label: 'Biskra', country_id: 1 },
        { label: 'Batna', country_id: 1 },
        { label: 'Sétif', country_id: 1 },
        { label: 'Sidi Bel Abbès', country_id: 1 },
        { label: 'Tiaret', country_id: 1 },
        { label: 'Chlef', country_id: 1 },
        { label: 'Béjaïa', country_id: 1 },
        { label: 'Tébessa', country_id: 1 },
        { label: 'Bordj Bou Arréridj', country_id: 1 },
        { label: 'Skikda', country_id: 1 },
        { label: 'Tlemcen', country_id: 1 },
        { label: 'Laghouat', country_id: 1 },
        { label: "M'Sila", country_id: 1 },
        { label: 'Souk Ahras', country_id: 1 },
        { label: 'El Eulma', country_id: 1 },
        { label: 'Blida', country_id: 1 },
        { label: 'El Oued', country_id: 1 },
        { label: 'Mostaganem', country_id: 1 },
        { label: 'Médéa', country_id: 1 },
        { label: 'Jijel', country_id: 1 },
        { label: 'Tizi Ouzou', country_id: 1 },
        { label: 'Ouargla', country_id: 1 },
        { label: 'Relizane', country_id: 1 },
        { label: 'Saïda', country_id: 1 },
        { label: 'Luanda', country_id: 2 },
        { label: 'Cabinda', country_id: 2 },
        { label: 'Huambo', country_id: 2 },
        { label: 'Lubango', country_id: 2 },
        { label: 'Cuito', country_id: 2 },
        { label: 'Malanje', country_id: 2 },
        { label: 'Benguela', country_id: 2 },
        { label: 'Lobito', country_id: 2 },
        { label: 'Uíge', country_id: 2 },
        { label: 'Namibe', country_id: 2 },
        { label: 'Luena', country_id: 2 },
        { label: 'Saurimo', country_id: 2 },
        { label: 'Soyo', country_id: 2 },
        { label: 'Sumbe', country_id: 2 },
        { label: "N'dalatando", country_id: 2 },
        { label: 'Lucapa', country_id: 2 },
        { label: 'Menongue', country_id: 2 },
        { label: 'Caxito', country_id: 2 },
        { label: 'Ondjiva', country_id: 2 },
        { label: 'Matala', country_id: 2 },
        { label: 'Tombwa', country_id: 2 },
        { label: 'Porto Amboim', country_id: 2 },
        { label: 'Caála', country_id: 2 },
        { label: 'Quipungo', country_id: 2 },
        { label: 'Namacunde', country_id: 2 },
        { label: 'Longonjo', country_id: 2 },
        { label: 'Baía Farta', country_id: 2 },
        { label: "M'banza-Kongo", country_id: 2 },
        { label: 'Amboim', country_id: 2 },
        { label: 'Dundo', country_id: 2 },
        { label: 'Cotonou', country_id: 3 },
        { label: 'Porto-Novo', country_id: 3 },
        { label: 'Parakou', country_id: 3 },
        { label: 'Natitingou', country_id: 3 },
        { label: 'Abomey', country_id: 3 },
        { label: 'Dassa-Zoumè', country_id: 3 },
        { label: 'Adjohoun', country_id: 3 },
        { label: 'Kérou', country_id: 3 },
        { label: 'Bembèrèkè', country_id: 3 },
        { label: 'Kalalé', country_id: 3 },
        { label: 'Malanville', country_id: 3 },
        { label: 'Abomey-Calavi', country_id: 3 },
        { label: 'Bantè', country_id: 3 },
        { label: "N'dali", country_id: 3 },
        { label: 'Djougou', country_id: 3 },
        { label: 'Lokossa', country_id: 3 },
        { label: 'Bohicon', country_id: 3 },
        { label: 'Kandi', country_id: 3 },
        { label: 'Kandi', country_id: 3 },
        { label: 'Kouandé', country_id: 3 },
        { label: 'Savé', country_id: 3 },
        { label: 'Savalou', country_id: 3 },
        { label: 'Sinendé', country_id: 3 },
        { label: 'Glazoué', country_id: 3 },
        { label: 'Kétou', country_id: 3 },
        { label: 'Comè', country_id: 3 },
        { label: 'Avrankou', country_id: 3 },
        { label: 'Cové', country_id: 3 },
        { label: 'Dangbo', country_id: 3 },
        { label: 'Athiémè', country_id: 3 },
        { label: 'Gaborone', country_id: 4 },
        { label: 'Francistown', country_id: 4 },
        { label: 'Molepolole', country_id: 4 },
        { label: 'Selebi-Phikwe', country_id: 4 },
        { label: 'Maun', country_id: 4 },
        { label: 'Serowe', country_id: 4 },
        { label: 'Kanye', country_id: 4 },
        { label: 'Mahalapye', country_id: 4 },
        { label: 'Mogoditshane', country_id: 4 },
        { label: 'Mochudi', country_id: 4 },
        { label: 'Lobatse', country_id: 4 },
        { label: 'Palapye', country_id: 4 },
        { label: 'Ramotswa', country_id: 4 },
        { label: 'Jwaneng', country_id: 4 },
        { label: 'Thamaga', country_id: 4 },
        { label: 'Letlhakane', country_id: 4 },
        { label: 'Tonota', country_id: 4 },
        { label: 'Kasane', country_id: 4 },
        { label: 'Kopong', country_id: 4 },
        { label: 'Ghanzi', country_id: 4 },
        { label: 'Bokaa', country_id: 4 },
        { label: 'Masunga', country_id: 4 },
        { label: 'Gabane', country_id: 4 },
        { label: 'Moshupa', country_id: 4 },
        { label: 'Tutume', country_id: 4 },
        { label: 'Rakops', country_id: 4 },
        { label: 'Mmathethe', country_id: 4 },
        { label: 'Good Hope', country_id: 4 },
        { label: 'Shakawe', country_id: 4 },
        { label: 'Bobonong', country_id: 4 },
        { label: 'Ouagadougou', country_id: 5 },
        { label: 'Bobo-Dioulasso', country_id: 5 },
        { label: 'Koudougou', country_id: 5 },
        { label: 'Ouahigouya', country_id: 5 },
        { label: 'Kaya', country_id: 5 },
        { label: 'Banfora', country_id: 5 },
        { label: 'Pouytenga', country_id: 5 },
        { label: 'Houndé', country_id: 5 },
        { label: "Fada N'Gourma", country_id: 5 },
        { label: 'Dédougou', country_id: 5 },
        { label: 'Djibo', country_id: 5 },
        { label: 'Tenkodogo', country_id: 5 },
        { label: 'Kongoussi', country_id: 5 },
        { label: 'Léo', country_id: 5 },
        { label: 'Koupéla', country_id: 5 },
        { label: 'Kombissiri', country_id: 5 },
        { label: 'Diapaga', country_id: 5 },
        { label: 'Manga', country_id: 5 },
        { label: 'Nouna', country_id: 5 },
        { label: 'Zorgho', country_id: 5 },
        { label: 'Yako', country_id: 5 },
        { label: 'Dori', country_id: 5 },
        { label: 'Gorom-Gorom', country_id: 5 },
        { label: 'Boussé', country_id: 5 },
        { label: 'Gaoua', country_id: 5 },
        { label: 'Boromo', country_id: 5 },
        { label: 'Boulsa', country_id: 5 },
        { label: 'Titao', country_id: 5 },
        { label: 'Garango', country_id: 5 },
        { label: 'Bogandé', country_id: 5 },
        { label: 'Bujumbura', country_id: 6 },
        { label: 'Gitega', country_id: 6 },
        { label: 'Muyinga', country_id: 6 },
        { label: 'Ngozi', country_id: 6 },
        { label: 'Ruyigi', country_id: 6 },
        { label: 'Kayanza', country_id: 6 },
        { label: 'Bururi', country_id: 6 },
        { label: 'Muramvya', country_id: 6 },
        { label: 'Makamba', country_id: 6 },
        { label: 'Rumonge', country_id: 6 },
        { label: 'Cibitoke', country_id: 6 },
        { label: 'Bubanza', country_id: 6 },
        { label: 'Karuzi', country_id: 6 },
        { label: 'Kirundo', country_id: 6 },
        { label: 'Rutana', country_id: 6 },
        { label: 'Mwaro', country_id: 6 },
        { label: 'Gatumba', country_id: 6 },
        { label: 'Gasorwe', country_id: 6 },
        { label: 'Matana', country_id: 6 },
        { label: 'Nyanza-Lac', country_id: 6 },
        { label: 'Gashikanwa', country_id: 6 },
        { label: 'Makebuko', country_id: 6 },
        { label: 'Butezi', country_id: 6 },
        { label: 'Buganda', country_id: 6 },
        { label: 'Busoni', country_id: 6 },
        { label: 'Rutegama', country_id: 6 },
        { label: 'Muruta', country_id: 6 },
        { label: 'Songa', country_id: 6 },
        { label: 'Rugazi', country_id: 6 },
        { label: 'Nyabikere', country_id: 6 },
        { label: 'Praia', country_id: 7 },
        { label: 'Mindelo', country_id: 7 },
        { label: 'Espargos', country_id: 7 },
        { label: 'Santa Maria', country_id: 7 },
        { label: 'Cova Figueira', country_id: 7 },
        { label: 'Assomada', country_id: 7 },
        { label: 'Pedra Badejo', country_id: 7 },
        { label: 'Santa Cruz', country_id: 7 },
        { label: 'Tarrafal', country_id: 7 },
        { label: 'São Domingos', country_id: 7 },
        { label: 'Ribeira Brava', country_id: 7 },
        { label: 'Sal Rei', country_id: 7 },
        { label: 'Porto Novo', country_id: 7 },
        { label: 'Calheta', country_id: 7 },
        { label: 'São Miguel', country_id: 7 },
        { label: 'Tarrafal de São Nicolau', country_id: 7 },
        { label: 'São Filipe', country_id: 7 },
        { label: 'Ribeira Grande', country_id: 7 },
        { label: 'Vila do Maio', country_id: 7 },
        { label: 'Vila Nova Sintra', country_id: 7 },
        { label: 'Cidade Velha', country_id: 7 },
        { label: 'Pombas', country_id: 7 },
        { label: 'Praia Branca', country_id: 7 },
        { label: 'João Teves', country_id: 7 },
        { label: 'Achada Falcão', country_id: 7 },
        { label: 'Palmeira', country_id: 7 },
        { label: 'Rabil', country_id: 7 },
        { label: 'Achada Monte', country_id: 7 },
        { label: 'Coculi', country_id: 7 },
        { label: 'Chã de Tanque', country_id: 7 },
        { label: 'Douala', country_id: 8 },
        { label: 'Yaoundé', country_id: 8 },
        { label: 'Garoua', country_id: 8 },
        { label: 'Kousseri', country_id: 8 },
        { label: 'Bamenda', country_id: 8 },
        { label: 'Maroua', country_id: 8 },
        { label: 'Bafoussam', country_id: 8 },
        { label: 'Mokolo', country_id: 8 },
        { label: 'Ngaoundéré', country_id: 8 },
        { label: 'Bertoua', country_id: 8 },
        { label: 'Edéa', country_id: 8 },
        { label: 'Loum', country_id: 8 },
        { label: 'Kumba', country_id: 8 },
        { label: 'Nkongsamba', country_id: 8 },
        { label: 'Mbouda', country_id: 8 },
        { label: 'Dschang', country_id: 8 },
        { label: 'Foumban', country_id: 8 },
        { label: 'Ebolowa', country_id: 8 },
        { label: 'Guider', country_id: 8 },
        { label: 'Foumbot', country_id: 8 },
        { label: 'Bafang', country_id: 8 },
        { label: 'Yagoua', country_id: 8 },
        { label: 'Mbalmayo', country_id: 8 },
        { label: 'Meiganga', country_id: 8 },
        { label: 'Bali', country_id: 8 },
        { label: 'Limbe', country_id: 8 },
        { label: 'Bafia', country_id: 8 },
        { label: 'Wum', country_id: 8 },
        { label: 'Bangangté', country_id: 8 },
        { label: 'Tiko', country_id: 8 },
        { label: 'Bangui', country_id: 9 },
        { label: 'Bimbo', country_id: 9 },
        { label: 'Bégoua', country_id: 9 },
        { label: 'Bossangoa', country_id: 9 },
        { label: 'Bouca', country_id: 9 },
        { label: 'Bozoum', country_id: 9 },
        { label: 'Kaga-Bandoro', country_id: 9 },
        { label: 'Bouar', country_id: 9 },
        { label: 'Mbaïki', country_id: 9 },
        { label: 'Sibut', country_id: 9 },
        { label: 'Obo', country_id: 9 },
        { label: 'Birao', country_id: 9 },
        { label: 'Mobaye', country_id: 9 },
        { label: 'Bria', country_id: 9 },
        { label: 'Bangassou', country_id: 9 },
        { label: 'Dekoa', country_id: 9 },
        { label: 'Nola', country_id: 9 },
        { label: 'Paoua', country_id: 9 },
        { label: 'Berbérati', country_id: 9 },
        { label: 'Baboua', country_id: 9 },
        { label: 'Bambari', country_id: 9 },
        { label: 'Ouadda', country_id: 9 },
        { label: 'Rafai', country_id: 9 },
        { label: 'Ngaoundaye', country_id: 9 },
        { label: 'Alindao', country_id: 9 },
        { label: 'Grimari', country_id: 9 },
        { label: 'Ndjoukou', country_id: 9 },
        { label: 'Boda', country_id: 9 },
        { label: 'Zangba', country_id: 9 },
        { label: 'Gambo', country_id: 9 },
        { label: "N'Djamena", country_id: 10 },
        { label: 'Moundou', country_id: 10 },
        { label: 'Sarh', country_id: 10 },
        { label: 'Abéché', country_id: 10 },
        { label: 'Kélo', country_id: 10 },
        { label: 'Am Timan', country_id: 10 },
        { label: 'Doba', country_id: 10 },
        { label: 'Pala', country_id: 10 },
        { label: 'Bongor', country_id: 10 },
        { label: 'Goz Beïda', country_id: 10 },
        { label: 'Mongo', country_id: 10 },
        { label: 'Fianga', country_id: 10 },
        { label: 'Massakory', country_id: 10 },
        { label: 'Bol', country_id: 10 },
        { label: 'Ati', country_id: 10 },
        { label: 'Léré', country_id: 10 },
        { label: 'Bitkine', country_id: 10 },
        { label: 'Biltine', country_id: 10 },
        { label: 'Oum Hadjer', country_id: 10 },
        { label: 'Faya-Largeau', country_id: 10 },
        { label: 'Massenya', country_id: 10 },
        { label: 'Bébédjia', country_id: 10 },
        { label: 'Koumra', country_id: 10 },
        { label: 'Iriba', country_id: 10 },
        { label: 'Béboto', country_id: 10 },
        { label: 'Bousso', country_id: 10 },
        { label: 'Kyabé', country_id: 10 },
        { label: 'Goundi', country_id: 10 },
        { label: 'Laï', country_id: 10 },
        { label: 'Baïbokoum', country_id: 10 },
        { label: 'Moroni', country_id: 11 },
        { label: 'Mutsamudu', country_id: 11 },
        { label: 'Fomboni', country_id: 11 },
        { label: 'Mitsamiouli', country_id: 11 },
        { label: 'Mbéni', country_id: 11 },
        { label: 'Domoni', country_id: 11 },
        { label: 'Iconi', country_id: 11 },
        { label: 'Wella', country_id: 11 },
        { label: 'Mboini', country_id: 11 },
        { label: 'Sima', country_id: 11 },
        { label: 'Foumbouni', country_id: 11 },
        { label: 'Ouani', country_id: 11 },
        { label: 'Nioumachoua', country_id: 11 },
        { label: 'Pidjani', country_id: 11 },
        { label: 'Koni-Djodjo', country_id: 11 },
        { label: 'Ouellah', country_id: 11 },
        { label: 'Bandrani', country_id: 11 },
        { label: 'Adda-Doueni', country_id: 11 },
        { label: 'Chomoni', country_id: 11 },
        { label: 'Djoyezi', country_id: 11 },
        { label: 'Mvouni', country_id: 11 },
        { label: 'Chindini', country_id: 11 },
        { label: 'Koni-Djodjo', country_id: 11 },
        { label: 'Bahani', country_id: 11 },
        { label: 'Barakani', country_id: 11 },
        { label: 'Pomoni', country_id: 11 },
        { label: 'Hagnamoida', country_id: 11 },
        { label: 'Tsembehou', country_id: 11 },
        { label: 'Mkazi', country_id: 11 },
        { label: 'Itsandra', country_id: 11 },
        { label: 'Kinshasa', country_id: 12 },
        { label: 'Lubumbashi', country_id: 12 },
        { label: 'Mbuji-Mayi', country_id: 12 },
        { label: 'Kananga', country_id: 12 },
        { label: 'Kisangani', country_id: 12 },
        { label: 'Bukavu', country_id: 12 },
        { label: 'Goma', country_id: 12 },
        { label: 'Kolwezi', country_id: 12 },
        { label: 'Likasi', country_id: 12 },
        { label: 'Tshikapa', country_id: 12 },
        { label: 'Matadi', country_id: 12 },
        { label: 'Mbandaka', country_id: 12 },
        { label: 'Kikwit', country_id: 12 },
        { label: 'Kalemie', country_id: 12 },
        { label: 'Kindu', country_id: 12 },
        { label: 'Boma', country_id: 12 },
        { label: 'Gemena', country_id: 12 },
        { label: 'Bandundu', country_id: 12 },
        { label: 'Zongo', country_id: 12 },
        { label: 'Isiro', country_id: 12 },
        { label: 'Bunia', country_id: 12 },
        { label: 'Lusambo', country_id: 12 },
        { label: 'Buta', country_id: 12 },
        { label: 'Kamina', country_id: 12 },
        { label: 'Kabinda', country_id: 12 },
        { label: 'Ilebo', country_id: 12 },
        { label: 'Bulungu', country_id: 12 },
        { label: 'Gbadolite', country_id: 12 },
        { label: 'Bukama', country_id: 12 },
        { label: 'Brazzaville', country_id: 12 },
        { label: 'Pointe-Noire', country_id: 12 },
        { label: 'Dolisie', country_id: 12 },
        { label: 'Nkayi', country_id: 12 },
        { label: 'Madingou', country_id: 12 },
        { label: 'Djambala', country_id: 12 },
        { label: 'Sibiti', country_id: 12 },
        { label: 'Kinkala', country_id: 12 },
        { label: 'Owando', country_id: 12 },
        { label: 'Ouésso', country_id: 12 },
        { label: 'Ewo', country_id: 12 },
        { label: 'Impfondo', country_id: 12 },
        { label: 'Mouyondzi', country_id: 12 },
        { label: 'Loandjili', country_id: 12 },
        { label: 'Gamboma', country_id: 12 },
        { label: 'Mossendjo', country_id: 12 },
        { label: 'Zanaga', country_id: 12 },
        { label: 'Mindouli', country_id: 12 },
        { label: 'Makoua', country_id: 12 },
        { label: 'Souanké', country_id: 12 },
        { label: 'Etoumbi', country_id: 12 },
        { label: 'Komono', country_id: 12 },
        { label: 'Ngabé', country_id: 12 },
        { label: 'Mossaka', country_id: 12 },
        { label: 'Mayoko', country_id: 12 },
        { label: 'Hinda', country_id: 12 },
        { label: 'Loutété', country_id: 12 },
        { label: 'Lekana', country_id: 12 },
        { label: 'Sembé', country_id: 12 },
        { label: 'Zanaga', country_id: 12 },
        { label: 'Abidjan', country_id: 13 },
        { label: 'Bouaké', country_id: 13 },
        { label: 'Daloa', country_id: 13 },
        { label: 'Korhogo', country_id: 13 },
        { label: 'San-Pédro', country_id: 13 },
        { label: 'Yamoussoukro', country_id: 13 },
        { label: 'Man', country_id: 13 },
        { label: 'Gagnoa', country_id: 13 },
        { label: 'Abengourou', country_id: 13 },
        { label: 'Ferkessédougou', country_id: 13 },
        { label: 'Divo', country_id: 13 },
        { label: 'Anyama', country_id: 13 },
        { label: 'Aboisso', country_id: 13 },
        { label: 'Sinfra', country_id: 13 },
        { label: 'Oumé', country_id: 13 },
        { label: 'Boundiali', country_id: 13 },
        { label: 'Séguéla', country_id: 13 },
        { label: 'Odienné', country_id: 13 },
        { label: 'Bouna', country_id: 13 },
        { label: 'Tabou', country_id: 13 },
        { label: 'Agnibilékrou', country_id: 13 },
        { label: 'Béoumi', country_id: 13 },
        { label: 'Bongouanou', country_id: 13 },
        { label: 'Biankouma', country_id: 13 },
        { label: 'Touba', country_id: 13 },
        { label: 'Vavoua', country_id: 13 },
        { label: 'Tiébissou', country_id: 13 },
        { label: 'Dabou', country_id: 13 },
        { label: 'Tengréla', country_id: 13 },
        { label: 'Minignan', country_id: 13 },
        { label: 'Djibouti City', country_id: 14 },
        { label: 'Ali Sabieh', country_id: 14 },
        { label: 'Dikhil', country_id: 14 },
        { label: 'Tadjoura', country_id: 14 },
        { label: 'Arta', country_id: 14 },
        { label: 'Obock', country_id: 14 },
        { label: 'Holhol', country_id: 14 },
        { label: 'Yoboki', country_id: 14 },
        { label: 'Galafi', country_id: 14 },
        { label: 'Dorra', country_id: 14 },
        { label: 'Loyada', country_id: 14 },
        { label: 'Alaïli Daoudé', country_id: 14 },
        { label: 'As Ela', country_id: 14 },
        { label: 'Balho', country_id: 14 },
        { label: 'Damerjog', country_id: 14 },
        { label: 'Goubato', country_id: 14 },
        { label: 'Damerjog', country_id: 14 },
        { label: 'Daggat', country_id: 14 },
        { label: 'Assamo', country_id: 14 },
        { label: 'Ali-Adde', country_id: 14 },
        { label: 'Chebelle', country_id: 14 },
        { label: 'Damerjog', country_id: 14 },
        { label: 'Doumera', country_id: 14 },
        { label: 'Damerjog', country_id: 14 },
        { label: 'Damerjog', country_id: 14 },
        { label: 'Damerjog', country_id: 14 },
        { label: 'Damerjog', country_id: 14 },
        { label: 'Damerjog', country_id: 14 },
        { label: 'Damerjog', country_id: 14 },
        { label: 'Damerjog', country_id: 14 },
        { label: 'Cairo', country_id: 15 },
        { label: 'Alexandria', country_id: 15 },
        { label: 'Giza', country_id: 15 },
        { label: 'Shubra El-Kheima', country_id: 15 },
        { label: 'Port Said', country_id: 15 },
        { label: 'Suez', country_id: 15 },
        { label: 'Luxor', country_id: 15 },
        { label: 'Mansoura', country_id: 15 },
        { label: 'El-Mahalla El-Kubra', country_id: 15 },
        { label: 'Tanta', country_id: 15 },
        { label: 'Asyut', country_id: 15 },
        { label: 'Ismailia', country_id: 15 },
        { label: 'Faiyum', country_id: 15 },
        { label: 'Zagazig', country_id: 15 },
        { label: 'Damietta', country_id: 15 },
        { label: 'Aswan', country_id: 15 },
        { label: 'Minya', country_id: 15 },
        { label: 'Beni Suef', country_id: 15 },
        { label: 'Qena', country_id: 15 },
        { label: 'Sohag', country_id: 15 },
        { label: 'Hurghada', country_id: 15 },
        { label: '6th of October', country_id: 15 },
        { label: 'Shibin El Kom', country_id: 15 },
        { label: 'Banha', country_id: 15 },
        { label: 'Arish', country_id: 15 },
        { label: 'Mallawi', country_id: 15 },
        { label: 'Bilbais', country_id: 15 },
        { label: 'Damietta', country_id: 15 },
        { label: 'Kafr El-Dawwar', country_id: 15 },
        { label: 'Desouk', country_id: 15 },
        { label: 'Malabo', country_id: 16 },
        { label: 'Bata', country_id: 16 },
        { label: 'San Antonio de Palé', country_id: 16 },
        { label: 'Rebola', country_id: 16 },
        { label: 'Evinayong', country_id: 16 },
        { label: 'Luba', country_id: 16 },
        { label: 'Baney', country_id: 16 },
        { label: 'Acurenam', country_id: 16 },
        { label: 'Ebebiyin', country_id: 16 },
        { label: 'Mongomo', country_id: 16 },
        { label: 'Añisoc', country_id: 16 },
        { label: 'Micomeseng', country_id: 16 },
        { label: 'Mbini', country_id: 16 },
        { label: 'Nsok', country_id: 16 },
        { label: 'Nsok-Nsomo', country_id: 16 },
        { label: 'Cogo', country_id: 16 },
        { label: 'Niefang', country_id: 16 },
        { label: 'Bikurga', country_id: 16 },
        { label: 'Mongomo', country_id: 16 },
        { label: 'Akonibe', country_id: 16 },
        { label: 'Riaba', country_id: 16 },
        { label: 'Ebebiyin', country_id: 16 },
        { label: 'Acurenam', country_id: 16 },
        { label: 'Baney', country_id: 16 },
        { label: 'Basakato del Oeste', country_id: 16 },
        { label: 'Nsok', country_id: 16 },
        { label: 'Micomeseng', country_id: 16 },
        { label: 'Mbini', country_id: 16 },
        { label: 'Riaba', country_id: 16 },
        { label: 'Cogo', country_id: 16 },
        { label: 'Asmara', country_id: 17 },
        { label: 'Keren', country_id: 17 },
        { label: 'Agordat', country_id: 17 },
        { label: 'Dekemhare', country_id: 17 },
        { label: 'Mendefera', country_id: 17 },
        { label: 'Massawa', country_id: 17 },
        { label: 'Adi Keyh', country_id: 17 },
        { label: 'Assab', country_id: 17 },
        { label: 'Ghinda', country_id: 17 },
        { label: 'Teseney', country_id: 17 },
        { label: 'Edd', country_id: 17 },
        { label: 'Himbirti', country_id: 17 },
        { label: 'Nefasit', country_id: 17 },
        { label: 'Adi Quala', country_id: 17 },
        { label: 'Senafe', country_id: 17 },
        { label: 'Segeneiti', country_id: 17 },
        { label: 'Afabet', country_id: 17 },
        { label: 'Beilul', country_id: 17 },
        { label: 'Mersa Fatuma', country_id: 17 },
        { label: 'Barentu', country_id: 17 },
        { label: 'Mersa Gulbub', country_id: 17 },
        { label: 'Areza', country_id: 17 },
        { label: 'Omhajer', country_id: 17 },
        { label: 'Adi Tekelezan', country_id: 17 },
        { label: 'Hazega', country_id: 17 },
        { label: 'Nacfa', country_id: 17 },
        { label: 'Shambuko', country_id: 17 },
        { label: 'Golij', country_id: 17 },
        { label: 'Zula', country_id: 17 },
        { label: 'Adi Abeto', country_id: 17 },
        { label: 'Mbabane', country_id: 18 },
        { label: 'Manzini', country_id: 18 },
        { label: 'Siteki', country_id: 18 },
        { label: 'Nhlangano', country_id: 18 },
        { label: 'Piggs Peak', country_id: 18 },
        { label: 'Hlatikulu', country_id: 18 },
        { label: 'Big Bend', country_id: 18 },
        { label: 'Malkerns', country_id: 18 },
        { label: 'Matsapha', country_id: 18 },
        { label: 'Bulembu', country_id: 18 },
        { label: 'Simunye', country_id: 18 },
        { label: 'Mhlume', country_id: 18 },
        { label: 'Lavumisa', country_id: 18 },
        { label: 'Bhunya', country_id: 18 },
        { label: 'Motshane', country_id: 18 },
        { label: 'Ezulwini', country_id: 18 },
        { label: 'Hluti', country_id: 18 },
        { label: 'Ngwenya', country_id: 18 },
        { label: 'Lomahasha', country_id: 18 },
        { label: 'Nsoko', country_id: 18 },
        { label: 'Kwaluseni', country_id: 18 },
        { label: 'Tshaneni', country_id: 18 },
        { label: 'Mankayane', country_id: 18 },
        { label: 'Maphiveni', country_id: 18 },
        { label: 'Gege', country_id: 18 },
        { label: 'Herefords', country_id: 18 },
        { label: 'Ludzeludze', country_id: 18 },
        { label: 'Lukhula', country_id: 18 },
        { label: 'Siphofaneni', country_id: 18 },
        { label: 'Emkhuzweni', country_id: 18 },
        { label: 'Addis Ababa', country_id: 19 },
        { label: 'Adama', country_id: 19 },
        { label: 'Gondar', country_id: 19 },
        { label: 'Bahir Dar', country_id: 19 },
        { label: 'Mekelle', country_id: 19 },
        { label: 'Jigjiga', country_id: 19 },
        { label: 'Dire Dawa', country_id: 19 },
        { label: 'Jimma', country_id: 19 },
        { label: 'Shashamane', country_id: 19 },
        { label: 'Bishoftu', country_id: 19 },
        { label: 'Dessie', country_id: 19 },
        { label: 'Adigrat', country_id: 19 },
        { label: 'Hawassa', country_id: 19 },
        { label: 'Nekemte', country_id: 19 },
        { label: 'Arba Minch', country_id: 19 },
        { label: 'Debre Zeyit', country_id: 19 },
        { label: 'Harar', country_id: 19 },
        { label: 'Dilla', country_id: 19 },
        { label: 'Sebeta', country_id: 19 },
        { label: 'Asella', country_id: 19 },
        { label: 'Bule Hora', country_id: 19 },
        { label: 'Gambela', country_id: 19 },
        { label: 'Axum', country_id: 19 },
        { label: 'Kombolcha', country_id: 19 },
        { label: 'Ambo', country_id: 19 },
        { label: 'Assosa', country_id: 19 },
        { label: 'Debre Berhan', country_id: 19 },
        { label: 'Woldia', country_id: 19 },
        { label: 'Batu', country_id: 19 },
        { label: 'Semera', country_id: 19 },
        { label: 'Libreville', country_id: 20 },
        { label: 'Port-Gentil', country_id: 20 },
        { label: 'Franceville', country_id: 20 },
        { label: 'Oyem', country_id: 20 },
        { label: 'Moanda', country_id: 20 },
        { label: 'Mouila', country_id: 20 },
        { label: 'Lambaréné', country_id: 20 },
        { label: 'Tchibanga', country_id: 20 },
        { label: 'Koulamoutou', country_id: 20 },
        { label: 'Makokou', country_id: 20 },
        { label: 'Bitam', country_id: 20 },
        { label: 'Gamba', country_id: 20 },
        { label: 'Mounana', country_id: 20 },
        { label: 'Ntoum', country_id: 20 },
        { label: 'Lastoursville', country_id: 20 },
        { label: 'Okondja', country_id: 20 },
        { label: 'Ndendé', country_id: 20 },
        { label: 'Booué', country_id: 20 },
        { label: 'Fougamou', country_id: 20 },
        { label: 'Ndjolé', country_id: 20 },
        { label: 'Mbigou', country_id: 20 },
        { label: 'Mayumba', country_id: 20 },
        { label: 'Mitzic', country_id: 20 },
        { label: 'Mékambo', country_id: 20 },
        { label: 'Léconi', country_id: 20 },
        { label: 'Mimongo', country_id: 20 },
        { label: 'Minvoul', country_id: 20 },
        { label: 'Medouneu', country_id: 20 },
        { label: 'Omboué', country_id: 20 },
        { label: 'Cocobeach', country_id: 20 },
        { label: 'Banjul', country_id: 21 },
        { label: 'Serekunda', country_id: 21 },
        { label: 'Brikama', country_id: 21 },
        { label: 'Bakau', country_id: 21 },
        { label: 'Lamin', country_id: 21 },
        { label: 'Farafenni', country_id: 21 },
        { label: 'Soma', country_id: 21 },
        { label: 'Janjanbureh', country_id: 21 },
        { label: 'Kaur', country_id: 21 },
        { label: 'Basse Santa Su', country_id: 21 },
        { label: 'Gunjur', country_id: 21 },
        { label: 'Sukuta', country_id: 21 },
        { label: 'Barra', country_id: 21 },
        { label: 'Tanji', country_id: 21 },
        { label: 'Georgetown', country_id: 21 },
        { label: 'Essau', country_id: 21 },
        { label: 'Brufut', country_id: 21 },
        { label: 'Sanyang', country_id: 21 },
        { label: 'Jambanjelly', country_id: 21 },
        { label: 'Sabi', country_id: 21 },
        { label: 'Albreda', country_id: 21 },
        { label: 'Wassu', country_id: 21 },
        { label: 'Bakoteh', country_id: 21 },
        { label: 'Kartong', country_id: 21 },
        { label: 'Kololi', country_id: 21 },
        { label: 'Fajara', country_id: 21 },
        { label: 'Kotu', country_id: 21 },
        { label: 'Bakindick', country_id: 21 },
        { label: 'Banjulinding', country_id: 21 },
        { label: 'Mansa Konko', country_id: 21 },
        { label: 'Accra', country_id: 22 },
        { label: 'Kumasi', country_id: 22 },
        { label: 'Sekondi-Takoradi', country_id: 22 },
        { label: 'Tamale', country_id: 22 },
        { label: 'Cape Coast', country_id: 22 },
        { label: 'Ho', country_id: 22 },
        { label: 'Koforidua', country_id: 22 },
        { label: 'Takoradi', country_id: 22 },
        { label: 'Obuasi', country_id: 22 },
        { label: 'Ejisu', country_id: 22 },
        { label: 'Yendi', country_id: 22 },
        { label: 'Winneba', country_id: 22 },
        { label: 'Mampong', country_id: 22 },
        { label: 'Konongo', country_id: 22 },
        { label: 'Sunyani', country_id: 22 },
        { label: 'Tarkwa', country_id: 22 },
        { label: 'Damongo', country_id: 22 },
        { label: 'Wa', country_id: 22 },
        { label: 'Bolgatanga', country_id: 22 },
        { label: 'Mankessim', country_id: 22 },
        { label: 'Offinso', country_id: 22 },
        { label: 'Nkawkaw', country_id: 22 },
        { label: 'Keta', country_id: 22 },
        { label: 'Agogo', country_id: 22 },
        { label: 'Tema', country_id: 22 },
        { label: 'Nsawam', country_id: 22 },
        { label: 'Kasoa', country_id: 22 },
        { label: 'Prestea', country_id: 22 },
        { label: 'Madina', country_id: 22 },
        { label: 'Techiman', country_id: 22 },
        { label: 'Conakry', country_id: 23 },
        { label: 'Nzérékoré', country_id: 23 },
        { label: 'Kindia', country_id: 23 },
        { label: 'Boké', country_id: 23 },
        { label: 'Kankan', country_id: 23 },
        { label: 'Faranah', country_id: 23 },
        { label: 'Kissidougou', country_id: 23 },
        { label: 'Siguiri', country_id: 23 },
        { label: 'Macenta', country_id: 23 },
        { label: 'Mamou', country_id: 23 },
        { label: 'Labé', country_id: 23 },
        { label: 'Kamsar', country_id: 23 },
        { label: 'Coyah', country_id: 23 },
        { label: 'Dubréka', country_id: 23 },
        { label: 'Guéckédou', country_id: 23 },
        { label: 'Kouroussa', country_id: 23 },
        { label: 'Koundara', country_id: 23 },
        { label: 'Dalaba', country_id: 23 },
        { label: 'Pita', country_id: 23 },
        { label: 'Télimélé', country_id: 23 },
        { label: 'Dabola', country_id: 23 },
        { label: 'Forécariah', country_id: 23 },
        { label: 'Fria', country_id: 23 },
        { label: 'Mandiana', country_id: 23 },
        { label: 'Tougué', country_id: 23 },
        { label: 'Mali', country_id: 23 },
        { label: 'Lola', country_id: 23 },
        { label: 'Beyla', country_id: 23 },
        { label: 'Faranah', country_id: 23 },
        { label: 'Siguiri', country_id: 23 },
        { label: 'Bissau', country_id: 24 },
        { label: 'Gabú', country_id: 24 },
        { label: 'Bafatá', country_id: 24 },
        { label: 'Cacheu', country_id: 24 },
        { label: 'Bolama', country_id: 24 },
        { label: 'Catió', country_id: 24 },
        { label: 'Buba', country_id: 24 },
        { label: 'Mansôa', country_id: 24 },
        { label: 'Gabú', country_id: 24 },
        { label: 'Farim', country_id: 24 },
        { label: 'Canchungo', country_id: 24 },
        { label: 'São Domingos', country_id: 24 },
        { label: 'Bambadinca', country_id: 24 },
        { label: 'Quebo', country_id: 24 },
        { label: 'Pirada', country_id: 24 },
        { label: 'Bigene', country_id: 24 },
        { label: 'Bissorã', country_id: 24 },
        { label: 'Bubaque', country_id: 24 },
        { label: 'Contuboel', country_id: 24 },
        { label: 'Bolama', country_id: 24 },
        { label: 'Cumeré', country_id: 24 },
        { label: 'Binar', country_id: 24 },
        { label: 'Caió', country_id: 24 },
        { label: 'Boé', country_id: 24 },
        { label: 'Cambaju', country_id: 24 },
        { label: 'Bedanda', country_id: 24 },
        { label: 'Empada', country_id: 24 },
        { label: 'Cacheu', country_id: 24 },
        { label: 'Canquelifá', country_id: 24 },
        { label: 'Contuboel', country_id: 24 },
        { label: 'Nairobi', country_id: 25 },
        { label: 'Mombasa', country_id: 25 },
        { label: 'Kisumu', country_id: 25 },
        { label: 'Nakuru', country_id: 25 },
        { label: 'Eldoret', country_id: 25 },
        { label: 'Thika', country_id: 25 },
        { label: 'Machakos', country_id: 25 },
        { label: 'Eldoret', country_id: 25 },
        { label: 'Meru', country_id: 25 },
        { label: 'Nyeri', country_id: 25 },
        { label: 'Kericho', country_id: 25 },
        { label: 'Bungoma', country_id: 25 },
        { label: 'Kakamega', country_id: 25 },
        { label: 'Nanyuki', country_id: 25 },
        { label: 'Narok', country_id: 25 },
        { label: 'Kisii', country_id: 25 },
        { label: 'Bomet', country_id: 25 },
        { label: 'Mbale', country_id: 25 },
        { label: 'Embu', country_id: 25 },
        { label: 'Kitui', country_id: 25 },
        { label: 'Malindi', country_id: 25 },
        { label: 'Ukunda', country_id: 25 },
        { label: 'Garissa', country_id: 25 },
        { label: 'Isiolo', country_id: 25 },
        { label: 'Marsabit', country_id: 25 },
        { label: 'Lodwar', country_id: 25 },
        { label: 'Wajir', country_id: 25 },
        { label: 'Mandera', country_id: 25 },
        { label: 'Lamu', country_id: 25 },
        { label: 'Voi', country_id: 25 },
        { label: 'Maseru', country_id: 26 },
        { label: 'Teyateyaneng', country_id: 26 },
        { label: 'Mafeteng', country_id: 26 },
        { label: 'Hlotse', country_id: 26 },
        { label: "Mohale's Hoek", country_id: 26 },
        { label: 'Maputsoe', country_id: 26 },
        { label: "Qacha's Nek", country_id: 26 },
        { label: 'Quthing', country_id: 26 },
        { label: 'Butha-Buthe', country_id: 26 },
        { label: 'Mokhotlong', country_id: 26 },
        { label: 'Thaba-Tseka', country_id: 26 },
        { label: 'Roma', country_id: 26 },
        { label: 'Peka', country_id: 26 },
        { label: 'Mazenod', country_id: 26 },
        { label: 'Morija', country_id: 26 },
        { label: 'Tsikoane', country_id: 26 },
        { label: 'Mohalinyane', country_id: 26 },
        { label: 'Mount Moorosi', country_id: 26 },
        { label: 'Siloe', country_id: 26 },
        { label: 'Linakeng', country_id: 26 },
        { label: 'Ha Lejone', country_id: 26 },
        { label: 'Sani Top', country_id: 26 },
        { label: 'Sekake', country_id: 26 },
        { label: 'Moyeni', country_id: 26 },
        { label: 'Nazareth', country_id: 26 },
        { label: 'Ha Tsolo', country_id: 26 },
        { label: 'Kolo', country_id: 26 },
        { label: 'Tsekong', country_id: 26 },
        { label: 'Kolonyama', country_id: 26 },
        { label: 'Ha Phororo', country_id: 26 },
        { label: 'Monrovia', country_id: 27 },
        { label: 'Gbarnga', country_id: 27 },
        { label: 'Buchanan', country_id: 27 },
        { label: 'Ganta', country_id: 27 },
        { label: 'Kakata', country_id: 27 },
        { label: 'Voinjama', country_id: 27 },
        { label: 'Harper', country_id: 27 },
        { label: 'Zwedru', country_id: 27 },
        { label: 'Greenville', country_id: 27 },
        { label: 'Tubmanburg', country_id: 27 },
        { label: 'Totota', country_id: 27 },
        { label: 'Bensonville', country_id: 27 },
        { label: 'Robertsport', country_id: 27 },
        { label: 'Marshall', country_id: 27 },
        { label: 'Fishtown', country_id: 27 },
        { label: 'Sanniquellie', country_id: 27 },
        { label: 'Barclayville', country_id: 27 },
        { label: 'Bopolu', country_id: 27 },
        { label: 'Tappita', country_id: 27 },
        { label: 'Brewerville', country_id: 27 },
        { label: 'Edina', country_id: 27 },
        { label: 'Suakoko', country_id: 27 },
        { label: 'Kolahun', country_id: 27 },
        { label: 'Sinje', country_id: 27 },
        { label: 'Weala', country_id: 27 },
        { label: 'Careysburg', country_id: 27 },
        { label: 'Yekepa', country_id: 27 },
        { label: 'Pleebo', country_id: 27 },
        { label: 'Cestos City', country_id: 27 },
        { label: 'St. John River City', country_id: 27 },
        { label: 'Tripoli', country_id: 28 },
        { label: 'Benghazi', country_id: 28 },
        { label: 'Misrata', country_id: 28 },
        { label: 'Zawiya', country_id: 28 },
        { label: 'Bayda', country_id: 28 },
        { label: 'Zliten', country_id: 28 },
        { label: 'Tobruk', country_id: 28 },
        { label: 'Sabha', country_id: 28 },
        { label: 'Khoms', country_id: 28 },
        { label: 'Derna', country_id: 28 },
        { label: 'Sabratha', country_id: 28 },
        { label: 'Ajdabiya', country_id: 28 },
        { label: 'Ghat', country_id: 28 },
        { label: 'Sirte', country_id: 28 },
        { label: 'Nalut', country_id: 28 },
        { label: 'Bani Walid', country_id: 28 },
        { label: 'Jalu', country_id: 28 },
        { label: 'Gharyan', country_id: 28 },
        { label: 'Awbari', country_id: 28 },
        { label: 'Tmassah', country_id: 28 },
        { label: 'Murzuk', country_id: 28 },
        { label: 'Ghadames', country_id: 28 },
        { label: 'Mizdah', country_id: 28 },
        { label: 'Al Qubbah', country_id: 28 },
        { label: 'Waddan', country_id: 28 },
        { label: 'Tarhuna', country_id: 28 },
        { label: 'Tajura', country_id: 28 },
        { label: 'Shahhat', country_id: 28 },
        { label: 'Zuwara', country_id: 28 },
        { label: 'Al Abyar', country_id: 28 },
        { label: 'Antananarivo', country_id: 29 },
        { label: 'Toamasina', country_id: 29 },
        { label: 'Antsirabe', country_id: 29 },
        { label: 'Mahajanga', country_id: 29 },
        { label: 'Fianarantsoa', country_id: 29 },
        { label: 'Toliara', country_id: 29 },
        { label: 'Antsiranana', country_id: 29 },
        { label: 'Ambovombe', country_id: 29 },
        { label: 'Antanifotsy', country_id: 29 },
        { label: 'Ambatondrazaka', country_id: 29 },
        { label: 'Sambava', country_id: 29 },
        { label: 'Mananjary', country_id: 29 },
        { label: 'Ambositra', country_id: 29 },
        { label: 'Farafangana', country_id: 29 },
        { label: 'Arivonimamo', country_id: 29 },
        { label: 'Antsohihy', country_id: 29 },
        { label: 'Mahanoro', country_id: 29 },
        { label: 'Amparafaravola', country_id: 29 },
        { label: 'Fenoarivo Atsinanana', country_id: 29 },
        { label: 'Mandritsara', country_id: 29 },
        { label: 'Belo Tsiribihina', country_id: 29 },
        { label: 'Antalaha', country_id: 29 },
        { label: 'Tolanaro', country_id: 29 },
        { label: 'Maevatanana', country_id: 29 },
        { label: 'Maintirano', country_id: 29 },
        { label: 'Ambohimahasoa', country_id: 29 },
        { label: 'Ambalavao', country_id: 29 },
        { label: 'Manakara', country_id: 29 },
        { label: 'Ampanihy', country_id: 29 },
        { label: 'Nosy Be', country_id: 29 },
        { label: 'Lilongwe', country_id: 30 },
        { label: 'Blantyre', country_id: 30 },
        { label: 'Mzuzu', country_id: 30 },
        { label: 'Zomba', country_id: 30 },
        { label: 'Mangochi', country_id: 30 },
        { label: 'Kasungu', country_id: 30 },
        { label: 'Nkhotakota', country_id: 30 },
        { label: 'Liwonde', country_id: 30 },
        { label: 'Salima', country_id: 30 },
        { label: 'Balaka', country_id: 30 },
        { label: 'Mchinji', country_id: 30 },
        { label: 'Mulanje', country_id: 30 },
        { label: 'Dedza', country_id: 30 },
        { label: 'Nsanje', country_id: 30 },
        { label: 'Chikwawa', country_id: 30 },
        { label: 'Ntcheu', country_id: 30 },
        { label: 'Karonga', country_id: 30 },
        { label: 'Ntchisi', country_id: 30 },
        { label: 'Rumphi', country_id: 30 },
        { label: 'Thyolo', country_id: 30 },
        { label: 'Dowa', country_id: 30 },
        { label: 'Phalombe', country_id: 30 },
        { label: 'Ntchisi', country_id: 30 },
        { label: 'Nkhata Bay', country_id: 30 },
        { label: 'Mwanza', country_id: 30 },
        { label: 'Chitipa', country_id: 30 },
        { label: 'Chiradzulu', country_id: 30 },
        { label: 'Likoma', country_id: 30 },
        { label: 'Machinga', country_id: 30 },
        { label: 'Mchinji', country_id: 30 },
        { label: 'Bamako', country_id: 31 },
        { label: 'Kati', country_id: 31 },
        { label: 'Sikasso', country_id: 31 },
        { label: 'Mopti', country_id: 31 },
        { label: 'Kayes', country_id: 31 },
        { label: 'Ségou', country_id: 31 },
        { label: 'Gao', country_id: 31 },
        { label: 'Timbuktu', country_id: 31 },
        { label: 'Koulikoro', country_id: 31 },
        { label: 'Kita', country_id: 31 },
        { label: 'Koutiala', country_id: 31 },
        { label: 'Bandiagara', country_id: 31 },
        { label: 'Niono', country_id: 31 },
        { label: 'Banamba', country_id: 31 },
        { label: 'Djenné', country_id: 31 },
        { label: 'Bougouni', country_id: 31 },
        { label: 'San', country_id: 31 },
        { label: 'Kolokani', country_id: 31 },
        { label: 'Yélimané', country_id: 31 },
        { label: 'Goundam', country_id: 31 },
        { label: 'Ansongo', country_id: 31 },
        { label: 'Youwarou', country_id: 31 },
        { label: 'Nioro du Sahel', country_id: 31 },
        { label: 'Kadiolo', country_id: 31 },
        { label: 'Bla', country_id: 31 },
        { label: 'Douentza', country_id: 31 },
        { label: 'Bafoulabé', country_id: 31 },
        { label: 'Macina', country_id: 31 },
        { label: 'Yanfolila', country_id: 31 },
        { label: 'Ténenkou', country_id: 31 },
        { label: 'Nouakchott', country_id: 32 },
        { label: 'Nouadhibou', country_id: 32 },
        { label: 'Kiffa', country_id: 32 },
        { label: 'Timbedra', country_id: 32 },
        { label: 'Ayoun el Atrous', country_id: 32 },
        { label: 'Kaédi', country_id: 32 },
        { label: 'Rosso', country_id: 32 },
        { label: 'Zouérat', country_id: 32 },
        { label: 'Atar', country_id: 32 },
        { label: 'Sélibaby', country_id: 32 },
        { label: 'Aleg', country_id: 32 },
        { label: 'Tidjikja', country_id: 32 },
        { label: 'Néma', country_id: 32 },
        { label: 'Boutilimit', country_id: 32 },
        { label: 'Boghé', country_id: 32 },
        { label: 'Maghama', country_id: 32 },
        { label: "R'Kiz", country_id: 32 },
        { label: 'Moudjéria', country_id: 32 },
        { label: "M'Bagne", country_id: 32 },
        { label: 'Foum Gleita', country_id: 32 },
        { label: 'Aoujeft', country_id: 32 },
        { label: 'Tamchakett', country_id: 32 },
        { label: 'Lexeiba', country_id: 32 },
        { label: 'Ould Yengé', country_id: 32 },
        { label: 'Fassala Néré', country_id: 32 },
        { label: 'Guerou', country_id: 32 },
        { label: 'Kankossa', country_id: 32 },
        { label: 'Bogué', country_id: 32 },
        { label: 'Djewol', country_id: 32 },
        { label: 'Rachid', country_id: 32 },
        { label: 'Vacoas-Phoenix', country_id: 33 },
        { label: 'Beau Bassin-Rose Hill', country_id: 33 },
        { label: 'Curepipe', country_id: 33 },
        { label: 'Port Louis', country_id: 33 },
        { label: 'Triolet', country_id: 33 },
        { label: 'Goodlands', country_id: 33 },
        { label: 'Centre de Flacq', country_id: 33 },
        { label: 'Quatre Bornes', country_id: 33 },
        { label: 'Souillac', country_id: 33 },
        { label: 'Mahebourg', country_id: 33 },
        { label: 'Saint Pierre', country_id: 33 },
        { label: 'Terre Rouge', country_id: 33 },
        { label: 'Rivière du Rempart', country_id: 33 },
        { label: 'Lalmatie', country_id: 33 },
        { label: 'Saint Julien d’Hotman', country_id: 33 },
        { label: 'Tamarin', country_id: 33 },
        { label: 'Grand Gaube', country_id: 33 },
        { label: 'Montagne Blanche', country_id: 33 },
        { label: 'Henrietta', country_id: 33 },
        { label: 'Chemin Grenier', country_id: 33 },
        { label: 'Flic en Flac', country_id: 33 },
        { label: 'Midlands', country_id: 33 },
        { label: 'Petit Raffray', country_id: 33 },
        { label: 'Bel Air', country_id: 33 },
        { label: 'Roches Noires', country_id: 33 },
        { label: 'La Laura Malenga', country_id: 33 },
        { label: 'Quartier Militaire', country_id: 33 },
        { label: 'Chamouny', country_id: 33 },
        { label: "Trou d'Eau Douce", country_id: 33 },
        { label: 'Cap Malheureux', country_id: 33 },
        { label: 'Casablanca', country_id: 34 },
        { label: 'Rabat', country_id: 34 },
        { label: 'Fès', country_id: 34 },
        { label: 'Tanger', country_id: 34 },
        { label: 'Marrakesh', country_id: 34 },
        { label: 'Béni Mellal', country_id: 34 },
        { label: 'Mohammedia', country_id: 34 },
        { label: 'Agadir', country_id: 34 },
        { label: 'El Jadida', country_id: 34 },
        { label: 'Salé', country_id: 34 },
        { label: 'Kénitra', country_id: 34 },
        { label: 'Oujda', country_id: 34 },
        { label: 'Berrechid', country_id: 34 },
        { label: 'Settat', country_id: 34 },
        { label: 'Safi', country_id: 34 },
        { label: 'Sidi Slimane', country_id: 34 },
        { label: 'Bouskoura', country_id: 34 },
        { label: 'Sidi Kacem', country_id: 34 },
        { label: 'Meknès', country_id: 34 },
        { label: 'Youssoufia', country_id: 34 },
        { label: 'Témara', country_id: 34 },
        { label: 'Taza', country_id: 34 },
        { label: 'Berkane', country_id: 34 },
        { label: 'Nouaceur', country_id: 34 },
        { label: 'Essaouira', country_id: 34 },
        { label: 'Tétouan', country_id: 34 },
        { label: 'Azemmour', country_id: 34 },
        { label: 'Skhirat', country_id: 34 },
        { label: 'El Hajeb', country_id: 34 },
        { label: 'Sidi Allal el Bahraoui', country_id: 34 },
        { label: 'Maputo', country_id: 35 },
        { label: 'Matola', country_id: 35 },
        { label: 'Nampula', country_id: 35 },
        { label: 'Beira', country_id: 35 },
        { label: 'Chimoio', country_id: 35 },
        { label: 'Quelimane', country_id: 35 },
        { label: 'Tete', country_id: 35 },
        { label: 'Nacala', country_id: 35 },
        { label: 'Lichinga', country_id: 35 },
        { label: 'Pemba', country_id: 35 },
        { label: 'Mocuba', country_id: 35 },
        { label: 'Gurúè', country_id: 35 },
        { label: 'Xai-Xai', country_id: 35 },
        { label: 'Maxixe', country_id: 35 },
        { label: 'Angoche', country_id: 35 },
        { label: 'Inhambane', country_id: 35 },
        { label: 'Cuamba', country_id: 35 },
        { label: 'Milange', country_id: 35 },
        { label: 'Maganja da Costa', country_id: 35 },
        { label: 'Manica', country_id: 35 },
        { label: 'Dondo', country_id: 35 },
        { label: 'Chókwè', country_id: 35 },
        { label: 'Massinga', country_id: 35 },
        { label: 'Montepuez', country_id: 35 },
        { label: 'Alto Molócuè', country_id: 35 },
        { label: 'Ilha de Moçambique', country_id: 35 },
        { label: 'Gondola', country_id: 35 },
        { label: 'Marracuene', country_id: 35 },
        { label: 'Moatize', country_id: 35 },
        { label: 'Pebane', country_id: 35 },
        { label: 'Windhoek', country_id: 36 },
        { label: 'Walvis Bay', country_id: 36 },
        { label: 'Swakopmund', country_id: 36 },
        { label: 'Otjiwarongo', country_id: 36 },
        { label: 'Oshakati', country_id: 36 },
        { label: 'Tsumeb', country_id: 36 },
        { label: 'Rundu', country_id: 36 },
        { label: 'Rehoboth', country_id: 36 },
        { label: 'Keetmanshoop', country_id: 36 },
        { label: 'Nkurenkuru', country_id: 36 },
        { label: 'Mariental', country_id: 36 },
        { label: 'Gobabis', country_id: 36 },
        { label: 'Outjo', country_id: 36 },
        { label: 'Karibib', country_id: 36 },
        { label: 'Katima Mulilo', country_id: 36 },
        { label: 'Ondangwa', country_id: 36 },
        { label: 'Outapi', country_id: 36 },
        { label: 'Eenhana', country_id: 36 },
        { label: 'Grootfontein', country_id: 36 },
        { label: 'Ruacana', country_id: 36 },
        { label: 'Okahandja', country_id: 36 },
        { label: 'Aranos', country_id: 36 },
        { label: 'Khorixas', country_id: 36 },
        { label: 'Usakos', country_id: 36 },
        { label: 'Okahao', country_id: 36 },
        { label: 'Omuthiya', country_id: 36 },
        { label: 'Divundu', country_id: 36 },
        { label: 'Opuwo', country_id: 36 },
        { label: 'Witvlei', country_id: 36 },
        { label: 'Ongwediva', country_id: 36 },
        { label: 'Niamey', country_id: 37 },
        { label: 'Zinder', country_id: 37 },
        { label: 'Maradi', country_id: 37 },
        { label: 'Tahoua', country_id: 37 },
        { label: 'Agadez', country_id: 37 },
        { label: 'Diffa', country_id: 37 },
        { label: 'Tillabéri', country_id: 37 },
        { label: 'Dosso', country_id: 37 },
        { label: 'Tessaoua', country_id: 37 },
        { label: 'Magaria', country_id: 37 },
        { label: 'Matamèye', country_id: 37 },
        { label: 'Madarounfa', country_id: 37 },
        { label: 'Illéla', country_id: 37 },
        { label: 'Gaya', country_id: 37 },
        { label: 'Arlit', country_id: 37 },
        { label: 'Dakoro', country_id: 37 },
        { label: 'Filingué', country_id: 37 },
        { label: 'Keita', country_id: 37 },
        { label: "N'Guigmi", country_id: 37 },
        { label: 'Mayahi', country_id: 37 },
        { label: 'Mirriah', country_id: 37 },
        { label: "Birni N'Konni", country_id: 37 },
        { label: 'Bouza', country_id: 37 },
        { label: 'Tibiri', country_id: 37 },
        { label: 'Gouré', country_id: 37 },
        { label: 'Ouallam', country_id: 37 },
        { label: 'Maïné-Soroa', country_id: 37 },
        { label: 'Tanout', country_id: 37 },
        { label: 'Abalak', country_id: 37 },
        { label: 'Say', country_id: 37 },
        { label: 'Lagos', country_id: 38 },
        { label: 'Kano', country_id: 38 },
        { label: 'Ibadan', country_id: 38 },
        { label: 'Abuja', country_id: 38 },
        { label: 'Port Harcourt', country_id: 38 },
        { label: 'Benin City', country_id: 38 },
        { label: 'Maiduguri', country_id: 38 },
        { label: 'Kaduna', country_id: 38 },
        { label: 'Onitsha', country_id: 38 },
        { label: 'Ilorin', country_id: 38 },
        { label: 'Enugu', country_id: 38 },
        { label: 'Oyo', country_id: 38 },
        { label: 'Abeokuta', country_id: 38 },
        { label: 'Owerri', country_id: 38 },
        { label: 'Uyo', country_id: 38 },
        { label: 'Warri', country_id: 38 },
        { label: 'Bauchi', country_id: 38 },
        { label: 'Calabar', country_id: 38 },
        { label: 'Akure', country_id: 38 },
        { label: 'Osogbo', country_id: 38 },
        { label: 'Katsina', country_id: 38 },
        { label: 'Ado-Ekiti', country_id: 38 },
        { label: 'Minna', country_id: 38 },
        { label: 'Jos', country_id: 38 },
        { label: 'Sokoto', country_id: 38 },
        { label: 'Jalingo', country_id: 38 },
        { label: 'Abakaliki', country_id: 38 },
        { label: 'Lokoja', country_id: 38 },
        { label: 'Birnin Kebbi', country_id: 38 },
        { label: 'Damaturu', country_id: 38 },
        { label: 'Kigali', country_id: 39 },
        { label: 'Musanze', country_id: 39 },
        { label: 'Rubavu', country_id: 39 },
        { label: 'Huye', country_id: 39 },
        { label: 'Rwamagana', country_id: 39 },
        { label: 'Muhanga', country_id: 39 },
        { label: 'Byumba', country_id: 39 },
        { label: 'Karongi', country_id: 39 },
        { label: 'Ruhango', country_id: 39 },
        { label: 'Nyagatare', country_id: 39 },
        { label: 'Gicumbi', country_id: 39 },
        { label: 'Rusizi', country_id: 39 },
        { label: 'Nyamata', country_id: 39 },
        { label: 'Nyanza', country_id: 39 },
        { label: 'Gakenke', country_id: 39 },
        { label: 'Kayonza', country_id: 39 },
        { label: 'Kamonyi', country_id: 39 },
        { label: 'Ngororero', country_id: 39 },
        { label: 'Kibungo', country_id: 39 },
        { label: 'Nyaruguru', country_id: 39 },
        { label: 'Nyamasheke', country_id: 39 },
        { label: 'Rulindo', country_id: 39 },
        { label: 'Gatsibo', country_id: 39 },
        { label: 'Nyabihu', country_id: 39 },
        { label: 'Kirehe', country_id: 39 },
        { label: 'Gisagara', country_id: 39 },
        { label: 'Bugesera', country_id: 39 },
        { label: 'Burera', country_id: 39 },
        { label: 'Karama', country_id: 39 },
        { label: 'Rubengera', country_id: 39 },
        { label: 'São Tomé', country_id: 40 },
        { label: 'Neves', country_id: 40 },
        { label: 'Santana', country_id: 40 },
        { label: 'Trindade', country_id: 40 },
        { label: 'Almas', country_id: 40 },
        { label: 'Pantufo', country_id: 40 },
        { label: 'Guadalupe', country_id: 40 },
        { label: 'Bombom', country_id: 40 },
        { label: 'Santo António', country_id: 40 },
        { label: 'São João dos Angolares', country_id: 40 },
        { label: 'Porto Alegre', country_id: 40 },
        { label: 'Santa Catarina', country_id: 40 },
        { label: 'Agostinho Neto', country_id: 40 },
        { label: 'Água Izé', country_id: 40 },
        { label: 'Monte Café', country_id: 40 },
        { label: 'Ribeira Afonso', country_id: 40 },
        { label: 'Conde', country_id: 40 },
        { label: 'Caixão Grande', country_id: 40 },
        { label: 'Diogo Simão', country_id: 40 },
        { label: 'Santo Amaro', country_id: 40 },
        { label: 'Bela Vista', country_id: 40 },
        { label: 'Diogo Vaz', country_id: 40 },
        { label: 'São Pedro', country_id: 40 },
        { label: 'Batepá', country_id: 40 },
        { label: 'Micondo', country_id: 40 },
        { label: 'Madalena', country_id: 40 },
        { label: 'Santa Margarida', country_id: 40 },
        { label: 'Trovoada', country_id: 40 },
        { label: 'Vila Moura', country_id: 40 },
        { label: 'Praia Melão', country_id: 40 },
        { label: 'Dakar', country_id: 41 },
        { label: 'Pikine', country_id: 41 },
        { label: 'Guédiawaye', country_id: 41 },
        { label: 'Rufisque', country_id: 41 },
        { label: 'Thiès', country_id: 41 },
        { label: 'Mbour', country_id: 41 },
        { label: 'Kaolack', country_id: 41 },
        { label: 'Ziguinchor', country_id: 41 },
        { label: 'Saint-Louis', country_id: 41 },
        { label: 'Diourbel', country_id: 41 },
        { label: 'Louga', country_id: 41 },
        { label: 'Tambacounda', country_id: 41 },
        { label: 'Kolda', country_id: 41 },
        { label: 'Fatick', country_id: 41 },
        { label: 'Kaffrine', country_id: 41 },
        { label: 'Kédougou', country_id: 41 },
        { label: 'Matam', country_id: 41 },
        { label: 'Sédhiou', country_id: 41 },
        { label: 'Vélingara', country_id: 41 },
        { label: 'Bignona', country_id: 41 },
        { label: 'Joal-Fadiouth', country_id: 41 },
        { label: 'Tivaouane', country_id: 41 },
        { label: 'Mbacké', country_id: 41 },
        { label: 'Richard-Toll', country_id: 41 },
        { label: 'Podor', country_id: 41 },
        { label: 'Saly Portudal', country_id: 41 },
        { label: 'Nioro du Rip', country_id: 41 },
        { label: 'Bignona', country_id: 41 },
        { label: 'Kahone', country_id: 41 },
        { label: 'Khombole', country_id: 41 },
        { label: 'Victoria', country_id: 42 },
        { label: 'Baie Sainte Anne', country_id: 42 },
        { label: 'La Passe', country_id: 42 },
        { label: 'Anse Boileau', country_id: 42 },
        { label: 'Anse Royale', country_id: 42 },
        { label: 'Beau Vallon', country_id: 42 },
        { label: 'Bel Ombre', country_id: 42 },
        { label: 'Cascade', country_id: 42 },
        { label: 'Glacis', country_id: 42 },
        { label: 'Grand Anse', country_id: 42 },
        { label: 'Pointe La Rue', country_id: 42 },
        { label: 'Takamaka', country_id: 42 },
        { label: 'Port Glaud', country_id: 42 },
        { label: 'Mont Fleuri', country_id: 42 },
        { label: 'Les Mamelles', country_id: 42 },
        { label: 'Roche Caiman', country_id: 42 },
        { label: 'Au Cap', country_id: 42 },
        { label: 'English River', country_id: 42 },
        { label: 'Plaisance', country_id: 42 },
        { label: 'Bel Air', country_id: 42 },
        { label: 'Anse Etoile', country_id: 42 },
        { label: 'Anse aux Pins', country_id: 42 },
        { label: 'St. Louis', country_id: 42 },
        { label: 'Ile Perseverance', country_id: 42 },
        { label: 'Grand Anse', country_id: 42 },
        { label: 'Anse Reunion', country_id: 42 },
        { label: 'Anse Volbert', country_id: 42 },
        { label: 'Pointe Au Sel', country_id: 42 },
        { label: 'Mont Buxton', country_id: 42 },
        { label: 'Ile du Port', country_id: 42 },
        { label: 'Freetown', country_id: 43 },
        { label: 'Bo', country_id: 43 },
        { label: 'Kenema', country_id: 43 },
        { label: 'Koidu', country_id: 43 },
        { label: 'Makeni', country_id: 43 },
        { label: 'Lunsar', country_id: 43 },
        { label: 'Port Loko', country_id: 43 },
        { label: 'Waterloo', country_id: 43 },
        { label: 'Kabala', country_id: 43 },
        { label: 'Segbwema', country_id: 43 },
        { label: 'Magburaka', country_id: 43 },
        { label: 'Kailahun', country_id: 43 },
        { label: 'Binkolo', country_id: 43 },
        { label: 'Bumpe', country_id: 43 },
        { label: 'Rokupr', country_id: 43 },
        { label: 'Kambia', country_id: 43 },
        { label: 'Yengema', country_id: 43 },
        { label: 'Bonthe', country_id: 43 },
        { label: 'Pendembu', country_id: 43 },
        { label: 'Blama', country_id: 43 },
        { label: 'Kamakwie', country_id: 43 },
        { label: 'Panguma', country_id: 43 },
        { label: 'Pujehun', country_id: 43 },
        { label: 'Kukuna', country_id: 43 },
        { label: 'Barma', country_id: 43 },
        { label: 'Boajibu', country_id: 43 },
        { label: 'Bunumbu', country_id: 43 },
        { label: 'Sumbuya', country_id: 43 },
        { label: 'Moyamba', country_id: 43 },
        { label: 'Mambolo', country_id: 43 },
        { label: 'Mogadishu', country_id: 44 },
        { label: 'Bosaso', country_id: 44 },
        { label: 'Hargeisa', country_id: 44 },
        { label: 'Marka', country_id: 44 },
        { label: 'Borama', country_id: 44 },
        { label: 'Galkayo', country_id: 44 },
        { label: 'Kismayo', country_id: 44 },
        { label: 'Dhusamareb', country_id: 44 },
        { label: 'Erigavo', country_id: 44 },
        { label: 'Garowe', country_id: 44 },
        { label: 'Jowhar', country_id: 44 },
        { label: 'Huddur', country_id: 44 },
        { label: 'Garbahaarreey', country_id: 44 },
        { label: "Bu'aale", country_id: 44 },
        { label: 'Baidoa', country_id: 44 },
        { label: 'Beledweyne', country_id: 44 },
        { label: 'Qardho', country_id: 44 },
        { label: 'Abudwak', country_id: 44 },
        { label: 'Burao', country_id: 44 },
        { label: 'Eyl', country_id: 44 },
        { label: 'Zeila', country_id: 44 },
        { label: 'Hobyo', country_id: 44 },
        { label: 'Jilib', country_id: 44 },
        { label: 'Diinsoor', country_id: 44 },
        { label: 'Luuq', country_id: 44 },
        { label: 'Balad', country_id: 44 },
        { label: 'Adado', country_id: 44 },
        { label: 'Iskushuban', country_id: 44 },
        { label: 'Las Khorey', country_id: 44 },
        { label: 'Las Anod', country_id: 44 },
        { label: 'Johannesburg', country_id: 45 },
        { label: 'Cape Town', country_id: 45 },
        { label: 'Durban', country_id: 45 },
        { label: 'Pretoria', country_id: 45 },
        { label: 'Port Elizabeth', country_id: 45 },
        { label: 'Bloemfontein', country_id: 45 },
        { label: 'Rustenburg', country_id: 45 },
        { label: 'Nelspruit', country_id: 45 },
        { label: 'Polokwane', country_id: 45 },
        { label: 'Mahikeng', country_id: 45 },
        { label: 'Soweto', country_id: 45 },
        { label: 'Pietermaritzburg', country_id: 45 },
        { label: 'George', country_id: 45 },
        { label: 'Vereeniging', country_id: 45 },
        { label: 'Benoni', country_id: 45 },
        { label: 'Tembisa', country_id: 45 },
        { label: 'Paarl', country_id: 45 },
        { label: 'Kimberley', country_id: 45 },
        { label: 'Boksburg', country_id: 45 },
        { label: 'East London', country_id: 45 },
        { label: 'Brakpan', country_id: 45 },
        { label: 'Richards Bay', country_id: 45 },
        { label: 'Uitenhage', country_id: 45 },
        { label: 'Thohoyandou', country_id: 45 },
        { label: 'Stellenbosch', country_id: 45 },
        { label: 'Kempton Park', country_id: 45 },
        { label: 'Newcastle', country_id: 45 },
        { label: 'Worcester', country_id: 45 },
        { label: 'Middelburg', country_id: 45 },
        { label: 'Knysna', country_id: 45 },
        { label: 'Juba', country_id: 46 },
        { label: 'Bor', country_id: 46 },
        { label: 'Yei', country_id: 46 },
        { label: 'Wau', country_id: 46 },
        { label: 'Malakal', country_id: 46 },
        { label: 'Pajok', country_id: 46 },
        { label: 'Gogrial', country_id: 46 },
        { label: 'Aweil', country_id: 46 },
        { label: 'Rumbek', country_id: 46 },
        { label: 'Yambio', country_id: 46 },
        { label: 'Nimule', country_id: 46 },
        { label: 'Torit', country_id: 46 },
        { label: 'Akobo', country_id: 46 },
        { label: 'Bentiu', country_id: 46 },
        { label: 'Wanyjok', country_id: 46 },
        { label: 'Fangak', country_id: 46 },
        { label: 'Kuajok', country_id: 46 },
        { label: 'Maridi', country_id: 46 },
        { label: 'Kajo Keji', country_id: 46 },
        { label: 'Leer', country_id: 46 },
        { label: 'Pibor', country_id: 46 },
        { label: 'Kodok', country_id: 46 },
        { label: 'Yirol', country_id: 46 },
        { label: 'Lainya', country_id: 46 },
        { label: 'Tonj', country_id: 46 },
        { label: 'Raja', country_id: 46 },
        { label: 'Kapoeta', country_id: 46 },
        { label: 'Renk', country_id: 46 },
        { label: 'Duk Padiet', country_id: 46 },
        { label: 'Pariang', country_id: 46 },
        { label: 'Khartoum', country_id: 47 },
        { label: 'Omdurman', country_id: 47 },
        { label: 'Khartoum North', country_id: 47 },
        { label: 'Wad Madani', country_id: 47 },
        { label: 'El-Obeid', country_id: 47 },
        { label: 'Port Sudan', country_id: 47 },
        { label: 'Nyala', country_id: 47 },
        { label: 'El Geneina', country_id: 47 },
        { label: 'El Fasher', country_id: 47 },
        { label: 'Kassala', country_id: 47 },
        { label: 'Atbara', country_id: 47 },
        { label: 'Sennar', country_id: 47 },
        { label: 'Ed Damazin', country_id: 47 },
        { label: 'Al Manaqil', country_id: 47 },
        { label: 'Kutum', country_id: 47 },
        { label: 'Babanusa', country_id: 47 },
        { label: 'Rabak', country_id: 47 },
        { label: 'Al Hasaheisa', country_id: 47 },
        { label: 'Shendi', country_id: 47 },
        { label: 'Aroma', country_id: 47 },
        { label: 'Tokar', country_id: 47 },
        { label: 'Gedaref', country_id: 47 },
        { label: 'Bara', country_id: 47 },
        { label: 'Kurmuk', country_id: 47 },
        { label: 'En Nahud', country_id: 47 },
        { label: 'Halfa al Jadeeda', country_id: 47 },
        { label: 'Kadugli', country_id: 47 },
        { label: 'Ed Daein', country_id: 47 },
        { label: 'Al Fula', country_id: 47 },
        { label: 'Singa', country_id: 47 },
        { label: 'Dar es Salaam', country_id: 48 },
        { label: 'Mwanza', country_id: 48 },
        { label: 'Arusha', country_id: 48 },
        { label: 'Mbeya', country_id: 48 },
        { label: 'Morogoro', country_id: 48 },
        { label: 'Tanga', country_id: 48 },
        { label: 'Dodoma', country_id: 48 },
        { label: 'Bukoba', country_id: 48 },
        { label: 'Kigoma', country_id: 48 },
        { label: 'Moshi', country_id: 48 },
        { label: 'Zanzibar Town', country_id: 48 },
        { label: 'Tabora', country_id: 48 },
        { label: 'Songea', country_id: 48 },
        { label: 'Singida', country_id: 48 },
        { label: 'Iringa', country_id: 48 },
        { label: 'Kibaha', country_id: 48 },
        { label: 'Sumbawanga', country_id: 48 },
        { label: 'Shinyanga', country_id: 48 },
        { label: 'Mtwara', country_id: 48 },
        { label: 'Lindi', country_id: 48 },
        { label: 'Musoma', country_id: 48 },
        { label: 'Geita', country_id: 48 },
        { label: 'Mpanda', country_id: 48 },
        { label: 'Njombe', country_id: 48 },
        { label: 'Bariadi', country_id: 48 },
        { label: 'Babati', country_id: 48 },
        { label: 'Nungwi', country_id: 48 },
        { label: 'Koani', country_id: 48 },
        { label: 'Misungwi', country_id: 48 },
        { label: 'Bagamoyo', country_id: 48 },
        { label: 'Lomé', country_id: 49 },
        { label: 'Sokodé', country_id: 49 },
        { label: 'Kara', country_id: 49 },
        { label: 'Kpalimé', country_id: 49 },
        { label: 'Atakpamé', country_id: 49 },
        { label: 'Bassar', country_id: 49 },
        { label: 'Tsévié', country_id: 49 },
        { label: 'Aného', country_id: 49 },
        { label: 'Mango', country_id: 49 },
        { label: 'Dapaong', country_id: 49 },
        { label: 'Tchamba', country_id: 49 },
        { label: 'Niamtougou', country_id: 49 },
        { label: 'Bafilo', country_id: 49 },
        { label: 'Notsé', country_id: 49 },
        { label: 'Sotouboua', country_id: 49 },
        { label: 'Vogan', country_id: 49 },
        { label: 'Badou', country_id: 49 },
        { label: 'Biankouri', country_id: 49 },
        { label: 'Tabligbo', country_id: 49 },
        { label: 'Kandé', country_id: 49 },
        { label: 'Amlamé', country_id: 49 },
        { label: 'Galangachi', country_id: 49 },
        { label: 'Kpagouda', country_id: 49 },
        { label: 'Agou', country_id: 49 },
        { label: 'Afagnan', country_id: 49 },
        { label: 'Baguida', country_id: 49 },
        { label: 'Elavagnon', country_id: 49 },
        { label: 'Baguida', country_id: 49 },
        { label: 'Aflao Gakli', country_id: 49 },
        { label: 'Aflao Sagbado', country_id: 49 },
        { label: 'Tunis', country_id: 50 },
        { label: 'Sfax', country_id: 50 },
        { label: 'Sousse', country_id: 50 },
        { label: 'Ettadhamen', country_id: 50 },
        { label: 'Kairouan', country_id: 50 },
        { label: 'Bizerte', country_id: 50 },
        { label: 'Gabès', country_id: 50 },
        { label: 'Ariana', country_id: 50 },
        { label: 'Gafsa', country_id: 50 },
        { label: 'Monastir', country_id: 50 },
        { label: 'Béja', country_id: 50 },
        { label: 'Medenine', country_id: 50 },
        { label: 'El Kef', country_id: 50 },
        { label: 'Sidi Bouzid', country_id: 50 },
        { label: 'Mahdia', country_id: 50 },
        { label: 'Jendouba', country_id: 50 },
        { label: 'Nabeul', country_id: 50 },
        { label: 'Tozeur', country_id: 50 },
        { label: 'Siliana', country_id: 50 },
        { label: 'Kasserine', country_id: 50 },
        { label: 'Manouba', country_id: 50 },
        { label: 'Tataouine', country_id: 50 },
        { label: 'Zaghouan', country_id: 50 },
        { label: 'Kebili', country_id: 50 },
        { label: 'Ben Arous', country_id: 50 },
        { label: 'Hammamet', country_id: 50 },
        { label: 'Douz', country_id: 50 },
        { label: 'Korba', country_id: 50 },
        { label: 'Menzel Temime', country_id: 50 },
        { label: 'Houmt Souk', country_id: 50 },
        { label: 'Kampala', country_id: 51 },
        { label: 'Nansana', country_id: 51 },
        { label: 'Kira', country_id: 51 },
        { label: 'Ssabagabo', country_id: 51 },
        { label: 'Mbarara', country_id: 51 },
        { label: 'Mukono', country_id: 51 },
        { label: 'Gulu', country_id: 51 },
        { label: 'Lira', country_id: 51 },
        { label: 'Mbale', country_id: 51 },
        { label: 'Entebbe', country_id: 51 },
        { label: 'Hoima', country_id: 51 },
        { label: 'Fort Portal', country_id: 51 },
        { label: 'Masaka', country_id: 51 },
        { label: 'Lugazi', country_id: 51 },
        { label: 'Jinja', country_id: 51 },
        { label: 'Arua', country_id: 51 },
        { label: 'Kabale', country_id: 51 },
        { label: 'Kasese', country_id: 51 },
        { label: 'Kitgum', country_id: 51 },
        { label: 'Soroti', country_id: 51 },
        { label: 'Adjumani', country_id: 51 },
        { label: 'Katakwi', country_id: 51 },
        { label: 'Kotido', country_id: 51 },
        { label: 'Moroto', country_id: 51 },
        { label: 'Moyo', country_id: 51 },
        { label: 'Nakapiripirit', country_id: 51 },
        { label: 'Nebbi', country_id: 51 },
        { label: 'Pader', country_id: 51 },
        { label: 'Yumbe', country_id: 51 },
        { label: 'Zombo', country_id: 51 },
        { label: 'Laâyoune', country_id: 52 },
        { label: 'Dakhla', country_id: 52 },
        { label: 'Smara', country_id: 52 },
        { label: 'Boujdour', country_id: 52 },
        { label: 'El Marsa', country_id: 52 },
        { label: 'Aousserd', country_id: 52 },
        { label: 'Guelta Zemmur', country_id: 52 },
        { label: 'Bir Anzarane', country_id: 52 },
        { label: 'Tichla', country_id: 52 },
        { label: 'Mahbes', country_id: 52 },
        { label: 'Umm Dreiga', country_id: 52 },
        { label: 'Jdiriya', country_id: 52 },
        { label: 'Farciya', country_id: 52 },
        { label: 'Sebaiera', country_id: 52 },
        { label: 'Lemseid', country_id: 52 },
        { label: 'El Argoub', country_id: 52 },
        { label: 'Bou Craa', country_id: 52 },
        { label: 'Tifariti', country_id: 52 },
        { label: 'Bir Gandus', country_id: 52 },
        { label: 'Zug', country_id: 52 },
        { label: 'Dougaj', country_id: 52 },
        { label: 'La Güera', country_id: 52 },
        { label: 'Agounit', country_id: 52 },
        { label: 'Bir Lehlou', country_id: 52 },
        { label: 'Meharrize', country_id: 52 },
        { label: 'Mijek', country_id: 52 },
        { label: 'Bir Tiguisit', country_id: 52 },
        { label: 'Aridal', country_id: 52 },
        { label: 'Guerguerat', country_id: 52 },
        { label: 'As-Sakn', country_id: 52 },
        { label: 'Lusaka', country_id: 53 },
        { label: 'Kitwe', country_id: 53 },
        { label: 'Ndola', country_id: 53 },
        { label: 'Livingstone', country_id: 53 },
        { label: 'Kabwe', country_id: 53 },
        { label: 'Chingola', country_id: 53 },
        { label: 'Mufulira', country_id: 53 },
        { label: 'Chipata', country_id: 53 },
        { label: 'Kasama', country_id: 53 },
        { label: 'Mazabuka', country_id: 53 },
        { label: 'Kafue', country_id: 53 },
        { label: 'Mansa', country_id: 53 },
        { label: 'Solwezi', country_id: 53 },
        { label: 'Chililabombwe', country_id: 53 },
        { label: 'Monze', country_id: 53 },
        { label: 'Kalomo', country_id: 53 },
        { label: 'Mkushi', country_id: 53 },
        { label: 'Chilanga', country_id: 53 },
        { label: 'Luanshya', country_id: 53 },
        { label: 'Chinsali', country_id: 53 },
        { label: 'Kalulushi', country_id: 53 },
        { label: 'Choma', country_id: 53 },
        { label: 'Chambishi', country_id: 53 },
        { label: 'Chongwe', country_id: 53 },
        { label: 'Serenje', country_id: 53 },
        { label: 'Mpulungu', country_id: 53 },
        { label: 'Samfya', country_id: 53 },
        { label: 'Isoka', country_id: 53 },
        { label: 'Mbala', country_id: 53 },
        { label: 'Mongu', country_id: 53 },
        { label: 'Harare', country_id: 54 },
        { label: 'Bulawayo', country_id: 54 },
        { label: 'Marondera', country_id: 54 },
        { label: 'Gweru', country_id: 54 },
        { label: 'Mutare', country_id: 54 },
        { label: 'Chinhoyi', country_id: 54 },
        { label: 'Masvingo', country_id: 54 },
        { label: 'Kwekwe', country_id: 54 },
        { label: 'Victoria Falls', country_id: 54 },
        { label: 'Bindura', country_id: 54 },
        { label: 'Ruwa', country_id: 54 },
        { label: 'Beitbridge', country_id: 54 },
        { label: 'Mazowe', country_id: 54 },
        { label: 'Murehwa', country_id: 54 },
        { label: 'Norton', country_id: 54 },
        { label: 'Zvishavane', country_id: 54 },
        { label: 'Rusape', country_id: 54 },
        { label: 'Chitungwiza', country_id: 54 },
        { label: 'Shurugwi', country_id: 54 },
        { label: 'Glendale', country_id: 54 },
        { label: 'Goromonzi', country_id: 54 },
        { label: 'Lupane', country_id: 54 },
        { label: 'Kadoma', country_id: 54 },
        { label: 'Redcliff', country_id: 54 },
        { label: 'Shamva', country_id: 54 },
        { label: 'Chipinge', country_id: 54 },
        { label: 'Mvuma', country_id: 54 },
        { label: 'Macheke', country_id: 54 },
        { label: 'Mount Darwin', country_id: 54 },
        { label: 'Hwange', country_id: 54 },
      ])
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
