import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'job_families'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.increments('id')
      table.string('label').notNullable()
    })

    this.defer(async (db) => {
      await db
        .table(this.tableName)
        .multiInsert([
          { label: 'Actuarial' },
          { label: 'Adult and Continuing Education' },
          { label: 'Advertising and Marketing' },
          { label: 'Agriculture and Sustainable Land Use' },
          { label: 'Allied Health Professions' },
          { label: 'Architecture' },
          { label: 'Assessment and Testing' },
          { label: 'Auditing' },
          { label: 'Banking Strategy and Operations' },
          { label: 'Beverage Production and Management' },
          { label: 'Bioinformatics and Computational Biology' },
          { label: 'Biomechanics' },
          { label: 'Broadcasting and Production' },
          { label: 'Building and Construction Services' },
          { label: 'Business Consulting ' },
          { label: 'Capital Markets' },
          { label: 'Carbon Management and Emissions Reduction' },
          { label: 'Casting and Talent Management' },
          { label: 'Claims Investigation and Fraud Detection' },
          { label: 'Climate Finance and Economics' },
          { label: 'Climate Risk Assessment and Management' },
          { label: 'Climate Science and Research' },
          { label: 'Climate Technology and Innovation' },
          { label: 'Climatology and Meteorology' },
          { label: 'Clinical Research' },
          { label: 'Community Development and Resilience' },
          { label: 'Compliance and Regulatory Affairs' },
          { label: 'Conservation and Natural Resource Management' },
          { label: 'Corporate Banking' },
          { label: 'Counseling and Guidance' },
          { label: 'Creative and Design' },
          { label: 'Creative Direction and Development' },
          { label: 'Crop Production' },
          { label: 'Culinary Arts and Kitchen Management ' },
          { label: 'Curriculum Development and Instructional Design' },
          { label: 'Customer Service and Support' },
          { label: 'Cybersecurity' },
          { label: 'Data Science and Analytics' },
          { label: 'Data Science and Analytics' },
          { label: 'Dental Services' },
          { label: 'Diagnostic Services' },
          { label: 'Digital Media and Content Creation' },
          { label: 'Digital Media and E-Publishing' },
          { label: 'Digital Media and Social Media' },
          { label: 'Early Childhood Education' },
          { label: 'Editorial and Journalism' },
          { label: 'Educational Psychology' },
          { label: 'Educational Technology and E-Learning' },
          { label: 'Emergency Medical Services' },
          { label: 'Engineering' },
          { label: 'Entertainment Production and Operations' },
          { label: 'Entertainment Technical Support and Engineering' },
          { label: 'Environmental and Climate' },
          { label: 'Environmental Compliance and Auditing' },
          { label: 'Environmental Consulting' },
          { label: 'Environmental Engineering' },
          { label: 'Environmental Geosciences' },
          { label: 'Environmental Informatics' },
          { label: 'Environmental Policy and Advocacy' },
          { label: 'Event Customer Service and Audience Relations' },
          { label: 'Event Management and Coordination' },
          { label: 'Event Security' },
          { label: 'Executive Protection' },
          { label: 'Exercise Physiology' },
          { label: 'Facilities & Plant Management' },
          { label: 'Facilities and Environmental Services' },
          { label: 'Farm Management and Operations' },
          { label: 'Finance' },
          { label: 'Financial Consulting ' },
          { label: 'Financial Services in Healthcare' },
          { label: 'Fisheries' },
          { label: 'Food and Beverage Service' },
          { label: 'Food Processing and Production' },
          { label: 'Forestry' },
          { label: 'Fundraising and Resource Mobilization' },
          { label: 'General Management' },
          { label: 'General Real Estate Management' },
          { label: 'Geology and Geophysics' },
          { label: 'Geospatial Data Analysis' },
          { label: 'Geospatial Technology and Innovation' },
          { label: 'Geotechnical Engineering' },
          { label: 'Health Education and Promotion' },
          { label: 'Health Information Management' },
          { label: 'Health IT and Informatics' },
          { label: 'Health Policy and Advocacy' },
          { label: 'Health Volunteer Services' },
          { label: 'Healthcare Economics and Market Access' },
          { label: 'Higher Education and Academic Affairs' },
          { label: 'Hospitality and Catering Management' },
          { label: 'Human Resource' },
          { label: 'Humanitarian Assistance and Disaster Response' },
          { label: 'Hydrogeology' },
          { label: 'ICT Operations' },
          { label: 'Information Governance/Management' },
          { label: 'Insurance Claims Management ' },
          { label: 'Insurance Product Development' },
          { label: 'Insurance Strategy and Operations' },
          { label: 'Investigations' },
          { label: 'Investment Banking' },
          { label: 'Laboratory Operations' },
          { label: 'Language Teaching and Linguistics' },
          { label: 'Legal and Compliance' },
          { label: 'Library and Media Services' },
          { label: 'Licensing and Rights Management' },
          { label: 'Life Science Data Analysis and Biostatistics' },
          { label: 'Literary and Rights Management' },
          { label: 'Livestock and Animal Husbandry' },
          { label: 'Location Analytics' },
          { label: 'Manufacturing and Production' },
          { label: 'Market Research' },
          { label: 'Marketing and Brand Management' },
          { label: 'Medical and Clinical Services' },
          { label: 'Mental Health Services' },
          { label: 'Mining' },
          { label: 'Monitoring, Evaluation, Research and Learning (MERL)' },
          { label: 'Nursing and Patient Care' },
          { label: 'Oceanography and Marine Geosciences' },
          { label: 'Oil and Gas' },
          { label: 'Operations and Administration' },
          { label: 'Packaging and Containers' },
          { label: 'Paleontology' },
          { label: 'Partnership and Stakeholder Relations Management' },
          { label: 'Payment Operations' },
          { label: 'Performance and Talent' },
          { label: 'Petroleum and Mining Geosciences' },
          { label: 'Pharmacy Services' },
          { label: 'Policy and Advocacy' },
          { label: 'Printing ' },
          { label: 'Product Development' },
          { label: 'Product Management' },
          { label: 'Production Management' },
          { label: 'Program Management' },
          { label: 'Project Management' },
          { label: 'Property Management' },
          { label: 'Public Health' },
          { label: 'Public Health and Climate' },
          { label: 'Public Relations' },
          { label: 'Public Relations and Communications' },
          { label: 'Quality Assurance' },
          { label: 'Real Estate Procurement, Strategy & Development' },
          { label: 'Rehabilitation Services' },
          { label: 'Remote Sensing and GIS (Geographic Information Systems)' },
          { label: 'Renewable Energy and Sustainability' },
          { label: 'Research and Academia' },
          { label: 'Research and Development' },
          { label: 'Retail Banking' },
          { label: 'Risk Management' },
          { label: 'Safety and Security' },
          { label: 'Safety Health and Environmental Services' },
          { label: 'Sales and Business Development' },
          { label: 'Scientific Research' },
          { label: 'Scientific Writing and Communication' },
          { label: 'Security Consulting' },
          { label: 'Security Management' },
          { label: 'Security Operations' },
          { label: 'Seismology and Volcanology' },
          { label: 'Social Services' },
          { label: 'Software Development' },
          { label: 'Soil Science and Agronomy' },
          { label: 'Sound and Music Production' },
          { label: 'Space Science' },
          { label: 'Special Education and Inclusive Practices' },
          { label: 'Sports Analytics' },
          { label: 'Sports Coaching' },
          { label: 'Sports Engineering' },
          { label: 'Sports Journalism and Media' },
          { label: 'Sports Management and Administration' },
          { label: 'Sports Medicine and Athletic Training' },
          { label: 'Sports Nutrition' },
          { label: 'Sports Performance Analysis' },
          { label: 'Sports Psychology' },
          { label: 'Sports Rehabilitation' },
          { label: 'Sports Research and Academia' },
          { label: 'Sports Technology and Innovation' },
          { label: 'Strength and Conditioning' },
          { label: 'Student Services and Support' },
          { label: 'Supply Chain' },
          { label: 'Surveillance and Monitoring' },
          { label: 'Tax Consulting' },
          { label: 'Teaching and Instruction' },
          { label: 'Technical Security (Systems and Equipment)' },
          { label: 'Therapeutic Services' },
          { label: 'Travel Agencies and Tour Operations' },
          { label: 'Treasury' },
          { label: 'Underwriting' },
          { label: 'Urban Planning and Green Building' },
          { label: 'Visual Arts and Design' },
          { label: 'Volunteer Services & Community Outreach' },
          { label: 'Wealth Management' },
          { label: 'Writing and Content Creation' },
        ])
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
